### ISSUE TITLE
Heads-up: find-cursor is now packaged in FreeBSD

### ISSUE THREAD

**Issue by 0mp** [arp242/find-cursor#10]
First of all, thanks for developing this cool piece of software. It is now available in the FreeBSD ports: https://www.freshports.org/x11/find-cursor/

**Comment by arp242** [comment]
Thanks :-)

I merged your LDFLAGS patch, mentioned your port in the README, added a manpage, and tagged `v1.2`. You should be able to remove that `post-configure` hack and replace `PORTDOCS`/`post-install-DOCS-on` with `MAN1=find-cursor` (IIRC, it's been many years since I made a FreeBSD port).
