### ISSUE TITLE
Program name missing from error messages

### ISSUE THREAD

**Issue by maramon** [arp242/find-cursor#13]
If environment variable DISPLAY is not set, the following error message is printed:

`(null): DISPLAY not set`

As far as I can see, it is intended that program name should be printed instead of "(null)". The issue can be fixed by removing line

`argv += optind;`

I wonder what the purpose of the line is.

**Comment by arp242** [comment]
> I wonder what the purpose of the line is.

It's intended for commands with positional arguments, like `filename1` and `filename2` in:

    $ foo -c opt filename1 filename2

But that serves no purpose here, as there are no such parameters. I don't often program in C, and probably copy/pasted that from what I considered a reputable documentation or example. While I don't tend to blindly copy/paste I missed that this serves no purpose here.

At any rate, I fixed it now. Thanks for reporting!
