### ISSUE TITLE
--repeat segmentation fault

### ISSUE THREAD

**Issue by step-** [arp242/find-cursor#16]
`find-cursor -r` faults when the repeat argument is missing. Fixed by adding `:` after `r` in `getopt_long` at [line 106](https://github.com/arp242/find-cursor/blob/79f2a2f504e17ef2b4ad4170abac2a3b394d5b42/find-cursor.c#L106).  Thank you for this program.

**Comment by arp242** [comment]
Thanks; fixed it!

**Comment by step-** [comment]
that was quick!
