### ISSUE TITLE
Compile in Fedora (solutions)

### ISSUE THREAD

**Issue by sefernet** [arp242/find-cursor#18]
Thanks for this app, its great!

Also, when I compile it in Fedora 30, give mi some errors, here are the solutions:
"Error fatal, no such file":
X11/Xlib.h = install package  "libX11-devel "
X11/extensions/Xdamage.h = libXdamage-devel
X11/extensions/Xrender.h = libXrender-devel
X11/extensions/shape = libXext-devel

Regards.

**Comment by arp242** [comment]
Cheers. Do you have the full error message? Just "no such file" isn't really too useful; there's probably some context somewhere which gives more information.

**Comment by arp242** [comment]
Ah wait, re-reading it, I think you solved it by installing those -devel packages? It's still early morning 😅 Would probably be useful documenting that; someone else [had similar issues on Ubuntu before](https://askubuntu.com/q/801252).
