### ISSUE TITLE
option to close find-cursor?

### ISSUE THREAD

**Issue by dianat100** [arp242/find-cursor#20]
Hello, I have created a launcher to launch the cursor whenever I want others to see my cursor on Skype. However, I don't see an easy way to close it once I am finished "pointing". I know I can kill it in the terminal, but each time I launch it, it is assigned a different ID number. How can I close the application with one click or universal command?

**Comment by arp242** [comment]
There's no real option to do that, and it wouldn't be easy to add either as IPC is kinda hard. It wouldn't be very different from `pkill find-cursor` anyway, so I recommend to just use that.

You can use a little script to check if there is a `find-cursor` process and kill it, or start a new one in the background if there isn't:

    if pgrep find-cursor; then
        pkill find-cursor
    else
        find-cursor -r0 &
    fi

If you map this to a key in your WM then it should work like a "toggle" key.

**Comment by dianat100** [comment]
Thank you. This works. Great script, keep it up.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Martin Tournoij <notifications@github.com> Date: 5/26/20  2:16 PM  (GMT+01:00) To: arp242/find-cursor <find-cursor@noreply.github.com> Cc: dianat100 <dianat100@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [arp242/find-cursor] option to close find-cursor? (#20) 
There's no real option to do that, and it wouldn't be easy to add either as IPC is kinda hard. It wouldn't be very different from pkill find-cursor anyway, so I recommend to just use that.
You can use a little script to check if there is a find-cursor process and kill it, or start a new one in the background if there isn't:
if pgrep find-cursor; then
    pkill find-cursor
else
    find-cursor -r0 &
fi

If you map this to a key in your WM then it should work like a "toggle" key.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arp242/find-cursor/issues/20#issuecomment-633987997",
"url": "https://github.com/arp242/find-cursor/issues/20#issuecomment-633987997",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by arp242** [comment]
Cheers, I added it to the README.
