### ISSUE TITLE
[Request] release version

### ISSUE THREAD

**Issue by ghost** [arp242/find-cursor#7]
Heya, mind making a release?

**Comment by arp242** [comment]
Hey there,

What advantage would making a "release" have for such a small project with practically no changes? While I get the reasons for larger projects (especially with multiple developers), I'm not sure if it adds anything here?

The way I've always seen it is that every git commit to master is a release; so the last "release" is aaefd2e.

**Comment by ghost** [comment]
Yea, I just try live by the rules..[2844](https://github.com/void-linux/void-packages/pull/2844)
Thanks for the reply, nice little tool by the way!
